# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build features and test feature branch

on:
  push:
    branches: [ "features/*" ]

jobs:
  build:
    runs-on: ubuntu-latest  #self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Pull and checkout from git repository
      run: |
        echo "pulling and checking out from git repository"
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install npm packages
      run: |
        echo "installing npm packages"
        npm cache clean --force
  #      npm install --force
  #      npm install -g @angular/cli@latest

    - name: Install angular cli
      run: npm install --force -g angular-cli@latest 

    # - name: run test and build angular app
    #   run: | 
    #     ng test --watch=false
    #     ng build
    #     echo "running test and build angular app"

    # - name: copy build to customer-back/src/main/resources/static
    #   run: |
    #     echo "copying build to customer-back/src/main/resources/static"
    #     cp -r dist/customer-front/* ../customer-back/src/main/resources/static/
    


    
    
    